# Generated by Django 5.0.6 on 2024-07-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gptcharacter_edit_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gptcharactertutor',
            options={},
        ),
        migrations.RemoveField(
            model_name='gptline',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='gptline',
            name='file_format',
        ),
        migrations.AddField(
            model_name='gptcharacter',
            name='username_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gptcharacteranalyst',
            name='username',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysts', to='app.gptcharacter', to_field='username'),
        ),
        migrations.AddField(
            model_name='gptcharacterstudent',
            name='notes',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gptcharacterstudent',
            name='username',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='app.gptcharacter', to_field='username'),
        ),
        migrations.AlterField(
            model_name='gptcharacter',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GptLineAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
                ('format', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment', to='app.gptline')),
            ],
            options={
                'db_table': 'gpt_line_attachment',
            },
        ),
    ]
