# Generated by Django 5.0.6 on 2024-07-16 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_gptcharactertutor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptcharactertutor',
            name='username',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutors', to='app.gptcharacter', to_field='username'),
        ),
        migrations.AlterField(
            model_name='gptcharactertutor',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gptcharactertutor',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
