# Generated by Django 5.0.6 on 2024-07-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gptcharactertutor_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptcharacter',
            name='username_temp',
        ),
    ]
