# Generated by Django 5.0.6 on 2024-07-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_gptcharacter_username_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptcharacterstudent',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gptcharacterstudent',
            name='school_grade',
            field=models.IntegerField(default=0),
        ),
    ]
