# Generated by Django 5.0.6 on 2024-07-17 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_gptcharacterstudent_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('role', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
                ('affiliation', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('school_grade', models.IntegerField(default=0, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.RemoveField(
            model_name='gptcharactertutor',
            name='username',
        ),
        migrations.RemoveField(
            model_name='gptcharactertutor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gptcharacterstudent',
            name='username',
        ),
        migrations.RemoveField(
            model_name='gptcharacterstudent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gptcharacteranalyst',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gptcharacteranalyst',
            name='username',
        ),
        migrations.AlterField(
            model_name='gptlabel',
            name='label_value1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gptlabel',
            name='label_value2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gptchat',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_chats', to='app.character'),
        ),
        migrations.AlterField(
            model_name='gptchat',
            name='tutor',
            field=models.ForeignKey(blank=True, db_column='tutor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor_chats', to='app.character'),
        ),
        migrations.AlterField(
            model_name='gptmodel',
            name='analyst',
            field=models.ForeignKey(blank=True, db_column='analyst', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.character'),
        ),
        migrations.DeleteModel(
            name='GptCharacter',
        ),
        migrations.DeleteModel(
            name='GptCharacterStudent',
        ),
        migrations.DeleteModel(
            name='GptCharacterTutor',
        ),
        migrations.DeleteModel(
            name='GptCharacterAnalyst',
        ),
    ]
