# Generated by Django 5.0.6 on 2024-07-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_gptchat_chat_rename_gptchatmodel_chatmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
