# Generated by Django 5.0.6 on 2024-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_character_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
