# Generated by Django 5.0.6 on 2024-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_character_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='school_grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
