# Generated by Django 5.0.6 on 2024-07-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_character_affiliation_alter_character_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='premis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.premis'),
        ),
    ]
