# Generated by Django 5.0.6 on 2024-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_documentation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='file_format',
            field=models.CharField(blank=True, null=True),
        ),
    ]
