# Generated by Django 5.0.6 on 2024-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_documentation_file_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='file_format',
        ),
        migrations.AddField(
            model_name='documentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
